CREATE SEQUENCE TBL_EMAIL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_EMAIL(
    ID INTEGER DEFAULT TBL_EMAIL_SEQ.NEXTVAL NOT NULL,
    REMETENTE VARCHAR(100) NOT NULL,
    COPIA VARCHAR(100) NOT NULL,
    CORPO_EMAIL VARCHAR(200) NOT NULL,
    ASSUNTO VARCHAR(100) NOT NULL,
    DESTINATARIO VARCHAR(100) NOT NULL,
    ANEXO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL
)